language: android

android:
  components:
    - build-tools-22.0.1
    - platform-tools
    - android-22
    - extra
    - sys-img-armeabi-v7a-android-22

jdk:
  - oraclejdk8

before_install:
  - mkdir -p $ANDROID_HOME/licenses
  - echo '8933bad161af4178b1185d1a37fbf41ea5269c55' > $ANDROID_HOME/licenses/android-sdk-license
  - echo '84831b9409646a918e30573bab4c9c91346d8abd' > $ANDROID_HOME/licenses/android-sdk-preview-license

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
