// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package org.kegbot.proto;

public final class Api {
  private Api() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MetaOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional uint32 total = 1;
    boolean hasTotal();
    int getTotal();
    
    // optional uint32 limit = 2;
    boolean hasLimit();
    int getLimit();
    
    // optional uint32 pos = 3;
    boolean hasPos();
    int getPos();
  }
  public static final class Meta extends
      com.google.protobuf.GeneratedMessage
      implements MetaOrBuilder {
    // Use Meta.newBuilder() to construct.
    private Meta(Builder builder) {
      super(builder);
    }
    private Meta(boolean noInit) {}
    
    private static final Meta defaultInstance;
    public static Meta getDefaultInstance() {
      return defaultInstance;
    }
    
    public Meta getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.kegbot.proto.Api.internal_static_Meta_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.kegbot.proto.Api.internal_static_Meta_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional uint32 total = 1;
    public static final int TOTAL_FIELD_NUMBER = 1;
    private int total_;
    public boolean hasTotal() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getTotal() {
      return total_;
    }
    
    // optional uint32 limit = 2;
    public static final int LIMIT_FIELD_NUMBER = 2;
    private int limit_;
    public boolean hasLimit() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getLimit() {
      return limit_;
    }
    
    // optional uint32 pos = 3;
    public static final int POS_FIELD_NUMBER = 3;
    private int pos_;
    public boolean hasPos() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getPos() {
      return pos_;
    }
    
    private void initFields() {
      total_ = 0;
      limit_ = 0;
      pos_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, total_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, limit_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(3, pos_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, total_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, limit_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, pos_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    @java.lang.Override
    protected Object writeReplace() throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.kegbot.proto.Api.Meta parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.kegbot.proto.Api.Meta parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.kegbot.proto.Api.Meta parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.kegbot.proto.Api.Meta parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.kegbot.proto.Api.Meta parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.kegbot.proto.Api.Meta parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.kegbot.proto.Api.Meta parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.kegbot.proto.Api.Meta parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.kegbot.proto.Api.Meta parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.kegbot.proto.Api.Meta parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.kegbot.proto.Api.Meta prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.kegbot.proto.Api.MetaOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.kegbot.proto.Api.internal_static_Meta_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.kegbot.proto.Api.internal_static_Meta_fieldAccessorTable;
      }
      
      // Construct using org.kegbot.proto.Api.Meta.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        total_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        limit_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        pos_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.kegbot.proto.Api.Meta.getDescriptor();
      }
      
      public org.kegbot.proto.Api.Meta getDefaultInstanceForType() {
        return org.kegbot.proto.Api.Meta.getDefaultInstance();
      }
      
      public org.kegbot.proto.Api.Meta build() {
        org.kegbot.proto.Api.Meta result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.kegbot.proto.Api.Meta buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.kegbot.proto.Api.Meta result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.kegbot.proto.Api.Meta buildPartial() {
        org.kegbot.proto.Api.Meta result = new org.kegbot.proto.Api.Meta(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.total_ = total_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.limit_ = limit_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.pos_ = pos_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.kegbot.proto.Api.Meta) {
          return mergeFrom((org.kegbot.proto.Api.Meta)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.kegbot.proto.Api.Meta other) {
        if (other == org.kegbot.proto.Api.Meta.getDefaultInstance()) return this;
        if (other.hasTotal()) {
          setTotal(other.getTotal());
        }
        if (other.hasLimit()) {
          setLimit(other.getLimit());
        }
        if (other.hasPos()) {
          setPos(other.getPos());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              total_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              limit_ = input.readUInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              pos_ = input.readUInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional uint32 total = 1;
      private int total_ ;
      public boolean hasTotal() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getTotal() {
        return total_;
      }
      public Builder setTotal(int value) {
        bitField0_ |= 0x00000001;
        total_ = value;
        onChanged();
        return this;
      }
      public Builder clearTotal() {
        bitField0_ = (bitField0_ & ~0x00000001);
        total_ = 0;
        onChanged();
        return this;
      }
      
      // optional uint32 limit = 2;
      private int limit_ ;
      public boolean hasLimit() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getLimit() {
        return limit_;
      }
      public Builder setLimit(int value) {
        bitField0_ |= 0x00000002;
        limit_ = value;
        onChanged();
        return this;
      }
      public Builder clearLimit() {
        bitField0_ = (bitField0_ & ~0x00000002);
        limit_ = 0;
        onChanged();
        return this;
      }
      
      // optional uint32 pos = 3;
      private int pos_ ;
      public boolean hasPos() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getPos() {
        return pos_;
      }
      public Builder setPos(int value) {
        bitField0_ |= 0x00000004;
        pos_ = value;
        onChanged();
        return this;
      }
      public Builder clearPos() {
        bitField0_ = (bitField0_ & ~0x00000004);
        pos_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:Meta)
    }
    
    static {
      defaultInstance = new Meta(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Meta)
  }
  
  public interface UserRegistrationRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string username = 1;
    boolean hasUsername();
    String getUsername();
    
    // required string email = 2;
    boolean hasEmail();
    String getEmail();
    
    // optional string password = 3;
    boolean hasPassword();
    String getPassword();
    
    // optional string gender = 4;
    boolean hasGender();
    String getGender();
    
    // optional string twitter_name = 5;
    boolean hasTwitterName();
    String getTwitterName();
  }
  public static final class UserRegistrationRequest extends
      com.google.protobuf.GeneratedMessage
      implements UserRegistrationRequestOrBuilder {
    // Use UserRegistrationRequest.newBuilder() to construct.
    private UserRegistrationRequest(Builder builder) {
      super(builder);
    }
    private UserRegistrationRequest(boolean noInit) {}
    
    private static final UserRegistrationRequest defaultInstance;
    public static UserRegistrationRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public UserRegistrationRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.kegbot.proto.Api.internal_static_UserRegistrationRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.kegbot.proto.Api.internal_static_UserRegistrationRequest_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string username = 1;
    public static final int USERNAME_FIELD_NUMBER = 1;
    private Object username_;
    public boolean hasUsername() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getUsername() {
      Object ref = username_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          username_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUsernameBytes() {
      Object ref = username_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string email = 2;
    public static final int EMAIL_FIELD_NUMBER = 2;
    private Object email_;
    public boolean hasEmail() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getEmail() {
      Object ref = email_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          email_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getEmailBytes() {
      Object ref = email_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string password = 3;
    public static final int PASSWORD_FIELD_NUMBER = 3;
    private Object password_;
    public boolean hasPassword() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getPassword() {
      Object ref = password_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          password_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPasswordBytes() {
      Object ref = password_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string gender = 4;
    public static final int GENDER_FIELD_NUMBER = 4;
    private Object gender_;
    public boolean hasGender() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getGender() {
      Object ref = gender_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          gender_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getGenderBytes() {
      Object ref = gender_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        gender_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string twitter_name = 5;
    public static final int TWITTER_NAME_FIELD_NUMBER = 5;
    private Object twitterName_;
    public boolean hasTwitterName() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getTwitterName() {
      Object ref = twitterName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          twitterName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTwitterNameBytes() {
      Object ref = twitterName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        twitterName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      username_ = "";
      email_ = "";
      password_ = "";
      gender_ = "";
      twitterName_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasUsername()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEmail()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUsernameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getEmailBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getPasswordBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getGenderBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getTwitterNameBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUsernameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getEmailBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getPasswordBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getGenderBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getTwitterNameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    @java.lang.Override
    protected Object writeReplace() throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.kegbot.proto.Api.UserRegistrationRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.kegbot.proto.Api.UserRegistrationRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.kegbot.proto.Api.UserRegistrationRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.kegbot.proto.Api.UserRegistrationRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.kegbot.proto.Api.UserRegistrationRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.kegbot.proto.Api.UserRegistrationRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.kegbot.proto.Api.UserRegistrationRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.kegbot.proto.Api.UserRegistrationRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.kegbot.proto.Api.UserRegistrationRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.kegbot.proto.Api.UserRegistrationRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.kegbot.proto.Api.UserRegistrationRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.kegbot.proto.Api.UserRegistrationRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.kegbot.proto.Api.internal_static_UserRegistrationRequest_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.kegbot.proto.Api.internal_static_UserRegistrationRequest_fieldAccessorTable;
      }
      
      // Construct using org.kegbot.proto.Api.UserRegistrationRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        username_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        email_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        password_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        gender_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        twitterName_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.kegbot.proto.Api.UserRegistrationRequest.getDescriptor();
      }
      
      public org.kegbot.proto.Api.UserRegistrationRequest getDefaultInstanceForType() {
        return org.kegbot.proto.Api.UserRegistrationRequest.getDefaultInstance();
      }
      
      public org.kegbot.proto.Api.UserRegistrationRequest build() {
        org.kegbot.proto.Api.UserRegistrationRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.kegbot.proto.Api.UserRegistrationRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.kegbot.proto.Api.UserRegistrationRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.kegbot.proto.Api.UserRegistrationRequest buildPartial() {
        org.kegbot.proto.Api.UserRegistrationRequest result = new org.kegbot.proto.Api.UserRegistrationRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.username_ = username_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.email_ = email_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.password_ = password_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.gender_ = gender_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.twitterName_ = twitterName_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.kegbot.proto.Api.UserRegistrationRequest) {
          return mergeFrom((org.kegbot.proto.Api.UserRegistrationRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.kegbot.proto.Api.UserRegistrationRequest other) {
        if (other == org.kegbot.proto.Api.UserRegistrationRequest.getDefaultInstance()) return this;
        if (other.hasUsername()) {
          setUsername(other.getUsername());
        }
        if (other.hasEmail()) {
          setEmail(other.getEmail());
        }
        if (other.hasPassword()) {
          setPassword(other.getPassword());
        }
        if (other.hasGender()) {
          setGender(other.getGender());
        }
        if (other.hasTwitterName()) {
          setTwitterName(other.getTwitterName());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasUsername()) {
          
          return false;
        }
        if (!hasEmail()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              username_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              email_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              password_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              gender_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              twitterName_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string username = 1;
      private Object username_ = "";
      public boolean hasUsername() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getUsername() {
        Object ref = username_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          username_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUsername(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        username_ = value;
        onChanged();
        return this;
      }
      public Builder clearUsername() {
        bitField0_ = (bitField0_ & ~0x00000001);
        username_ = getDefaultInstance().getUsername();
        onChanged();
        return this;
      }
      void setUsername(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        username_ = value;
        onChanged();
      }
      
      // required string email = 2;
      private Object email_ = "";
      public boolean hasEmail() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getEmail() {
        Object ref = email_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setEmail(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        email_ = value;
        onChanged();
        return this;
      }
      public Builder clearEmail() {
        bitField0_ = (bitField0_ & ~0x00000002);
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      void setEmail(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        email_ = value;
        onChanged();
      }
      
      // optional string password = 3;
      private Object password_ = "";
      public boolean hasPassword() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getPassword() {
        Object ref = password_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          password_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPassword(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        password_ = value;
        onChanged();
        return this;
      }
      public Builder clearPassword() {
        bitField0_ = (bitField0_ & ~0x00000004);
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      void setPassword(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        password_ = value;
        onChanged();
      }
      
      // optional string gender = 4;
      private Object gender_ = "";
      public boolean hasGender() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getGender() {
        Object ref = gender_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          gender_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setGender(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        gender_ = value;
        onChanged();
        return this;
      }
      public Builder clearGender() {
        bitField0_ = (bitField0_ & ~0x00000008);
        gender_ = getDefaultInstance().getGender();
        onChanged();
        return this;
      }
      void setGender(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        gender_ = value;
        onChanged();
      }
      
      // optional string twitter_name = 5;
      private Object twitterName_ = "";
      public boolean hasTwitterName() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getTwitterName() {
        Object ref = twitterName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          twitterName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTwitterName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        twitterName_ = value;
        onChanged();
        return this;
      }
      public Builder clearTwitterName() {
        bitField0_ = (bitField0_ & ~0x00000010);
        twitterName_ = getDefaultInstance().getTwitterName();
        onChanged();
        return this;
      }
      void setTwitterName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        twitterName_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:UserRegistrationRequest)
    }
    
    static {
      defaultInstance = new UserRegistrationRequest(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:UserRegistrationRequest)
  }
  
  public interface RecordDrinkRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string tap_name = 1;
    boolean hasTapName();
    String getTapName();
    
    // required uint32 ticks = 2;
    boolean hasTicks();
    int getTicks();
    
    // optional float volume_ml = 3;
    boolean hasVolumeMl();
    float getVolumeMl();
    
    // optional string username = 4;
    boolean hasUsername();
    String getUsername();
    
    // optional uint32 seconds_ago = 5 [default = 0];
    boolean hasSecondsAgo();
    int getSecondsAgo();
    
    // optional string record_date = 6;
    boolean hasRecordDate();
    String getRecordDate();
    
    // optional uint32 duration_seconds = 7;
    boolean hasDurationSeconds();
    int getDurationSeconds();
    
    // optional string auth_token = 8;
    boolean hasAuthToken();
    String getAuthToken();
    
    // optional bool spilled = 9;
    boolean hasSpilled();
    boolean getSpilled();
    
    // optional string shout = 10;
    boolean hasShout();
    String getShout();
  }
  public static final class RecordDrinkRequest extends
      com.google.protobuf.GeneratedMessage
      implements RecordDrinkRequestOrBuilder {
    // Use RecordDrinkRequest.newBuilder() to construct.
    private RecordDrinkRequest(Builder builder) {
      super(builder);
    }
    private RecordDrinkRequest(boolean noInit) {}
    
    private static final RecordDrinkRequest defaultInstance;
    public static RecordDrinkRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public RecordDrinkRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.kegbot.proto.Api.internal_static_RecordDrinkRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.kegbot.proto.Api.internal_static_RecordDrinkRequest_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string tap_name = 1;
    public static final int TAP_NAME_FIELD_NUMBER = 1;
    private Object tapName_;
    public boolean hasTapName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getTapName() {
      Object ref = tapName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          tapName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTapNameBytes() {
      Object ref = tapName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        tapName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required uint32 ticks = 2;
    public static final int TICKS_FIELD_NUMBER = 2;
    private int ticks_;
    public boolean hasTicks() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getTicks() {
      return ticks_;
    }
    
    // optional float volume_ml = 3;
    public static final int VOLUME_ML_FIELD_NUMBER = 3;
    private float volumeMl_;
    public boolean hasVolumeMl() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public float getVolumeMl() {
      return volumeMl_;
    }
    
    // optional string username = 4;
    public static final int USERNAME_FIELD_NUMBER = 4;
    private Object username_;
    public boolean hasUsername() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getUsername() {
      Object ref = username_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          username_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUsernameBytes() {
      Object ref = username_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional uint32 seconds_ago = 5 [default = 0];
    public static final int SECONDS_AGO_FIELD_NUMBER = 5;
    private int secondsAgo_;
    public boolean hasSecondsAgo() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public int getSecondsAgo() {
      return secondsAgo_;
    }
    
    // optional string record_date = 6;
    public static final int RECORD_DATE_FIELD_NUMBER = 6;
    private Object recordDate_;
    public boolean hasRecordDate() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public String getRecordDate() {
      Object ref = recordDate_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          recordDate_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getRecordDateBytes() {
      Object ref = recordDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        recordDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional uint32 duration_seconds = 7;
    public static final int DURATION_SECONDS_FIELD_NUMBER = 7;
    private int durationSeconds_;
    public boolean hasDurationSeconds() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public int getDurationSeconds() {
      return durationSeconds_;
    }
    
    // optional string auth_token = 8;
    public static final int AUTH_TOKEN_FIELD_NUMBER = 8;
    private Object authToken_;
    public boolean hasAuthToken() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public String getAuthToken() {
      Object ref = authToken_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          authToken_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getAuthTokenBytes() {
      Object ref = authToken_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        authToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional bool spilled = 9;
    public static final int SPILLED_FIELD_NUMBER = 9;
    private boolean spilled_;
    public boolean hasSpilled() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    public boolean getSpilled() {
      return spilled_;
    }
    
    // optional string shout = 10;
    public static final int SHOUT_FIELD_NUMBER = 10;
    private Object shout_;
    public boolean hasShout() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    public String getShout() {
      Object ref = shout_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          shout_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getShoutBytes() {
      Object ref = shout_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        shout_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      tapName_ = "";
      ticks_ = 0;
      volumeMl_ = 0F;
      username_ = "";
      secondsAgo_ = 0;
      recordDate_ = "";
      durationSeconds_ = 0;
      authToken_ = "";
      spilled_ = false;
      shout_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasTicks()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTapNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, ticks_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeFloat(3, volumeMl_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getUsernameBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeUInt32(5, secondsAgo_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getRecordDateBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeUInt32(7, durationSeconds_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getAuthTokenBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBool(9, spilled_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBytes(10, getShoutBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTapNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, ticks_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, volumeMl_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getUsernameBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, secondsAgo_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getRecordDateBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(7, durationSeconds_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getAuthTokenBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(9, spilled_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, getShoutBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    @java.lang.Override
    protected Object writeReplace() throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.kegbot.proto.Api.RecordDrinkRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.kegbot.proto.Api.RecordDrinkRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.kegbot.proto.Api.RecordDrinkRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.kegbot.proto.Api.RecordDrinkRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.kegbot.proto.Api.RecordDrinkRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.kegbot.proto.Api.RecordDrinkRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.kegbot.proto.Api.RecordDrinkRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.kegbot.proto.Api.RecordDrinkRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.kegbot.proto.Api.RecordDrinkRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.kegbot.proto.Api.RecordDrinkRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.kegbot.proto.Api.RecordDrinkRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.kegbot.proto.Api.RecordDrinkRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.kegbot.proto.Api.internal_static_RecordDrinkRequest_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.kegbot.proto.Api.internal_static_RecordDrinkRequest_fieldAccessorTable;
      }
      
      // Construct using org.kegbot.proto.Api.RecordDrinkRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        tapName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        ticks_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        volumeMl_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000004);
        username_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        secondsAgo_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        recordDate_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        durationSeconds_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        authToken_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        spilled_ = false;
        bitField0_ = (bitField0_ & ~0x00000100);
        shout_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.kegbot.proto.Api.RecordDrinkRequest.getDescriptor();
      }
      
      public org.kegbot.proto.Api.RecordDrinkRequest getDefaultInstanceForType() {
        return org.kegbot.proto.Api.RecordDrinkRequest.getDefaultInstance();
      }
      
      public org.kegbot.proto.Api.RecordDrinkRequest build() {
        org.kegbot.proto.Api.RecordDrinkRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.kegbot.proto.Api.RecordDrinkRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.kegbot.proto.Api.RecordDrinkRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.kegbot.proto.Api.RecordDrinkRequest buildPartial() {
        org.kegbot.proto.Api.RecordDrinkRequest result = new org.kegbot.proto.Api.RecordDrinkRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.tapName_ = tapName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.ticks_ = ticks_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.volumeMl_ = volumeMl_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.username_ = username_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.secondsAgo_ = secondsAgo_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.recordDate_ = recordDate_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.durationSeconds_ = durationSeconds_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.authToken_ = authToken_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.spilled_ = spilled_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.shout_ = shout_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.kegbot.proto.Api.RecordDrinkRequest) {
          return mergeFrom((org.kegbot.proto.Api.RecordDrinkRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.kegbot.proto.Api.RecordDrinkRequest other) {
        if (other == org.kegbot.proto.Api.RecordDrinkRequest.getDefaultInstance()) return this;
        if (other.hasTapName()) {
          setTapName(other.getTapName());
        }
        if (other.hasTicks()) {
          setTicks(other.getTicks());
        }
        if (other.hasVolumeMl()) {
          setVolumeMl(other.getVolumeMl());
        }
        if (other.hasUsername()) {
          setUsername(other.getUsername());
        }
        if (other.hasSecondsAgo()) {
          setSecondsAgo(other.getSecondsAgo());
        }
        if (other.hasRecordDate()) {
          setRecordDate(other.getRecordDate());
        }
        if (other.hasDurationSeconds()) {
          setDurationSeconds(other.getDurationSeconds());
        }
        if (other.hasAuthToken()) {
          setAuthToken(other.getAuthToken());
        }
        if (other.hasSpilled()) {
          setSpilled(other.getSpilled());
        }
        if (other.hasShout()) {
          setShout(other.getShout());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasTicks()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              tapName_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              ticks_ = input.readUInt32();
              break;
            }
            case 29: {
              bitField0_ |= 0x00000004;
              volumeMl_ = input.readFloat();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              username_ = input.readBytes();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              secondsAgo_ = input.readUInt32();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              recordDate_ = input.readBytes();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              durationSeconds_ = input.readUInt32();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              authToken_ = input.readBytes();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              spilled_ = input.readBool();
              break;
            }
            case 82: {
              bitField0_ |= 0x00000200;
              shout_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string tap_name = 1;
      private Object tapName_ = "";
      public boolean hasTapName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getTapName() {
        Object ref = tapName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          tapName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTapName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        tapName_ = value;
        onChanged();
        return this;
      }
      public Builder clearTapName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        tapName_ = getDefaultInstance().getTapName();
        onChanged();
        return this;
      }
      void setTapName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        tapName_ = value;
        onChanged();
      }
      
      // required uint32 ticks = 2;
      private int ticks_ ;
      public boolean hasTicks() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getTicks() {
        return ticks_;
      }
      public Builder setTicks(int value) {
        bitField0_ |= 0x00000002;
        ticks_ = value;
        onChanged();
        return this;
      }
      public Builder clearTicks() {
        bitField0_ = (bitField0_ & ~0x00000002);
        ticks_ = 0;
        onChanged();
        return this;
      }
      
      // optional float volume_ml = 3;
      private float volumeMl_ ;
      public boolean hasVolumeMl() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public float getVolumeMl() {
        return volumeMl_;
      }
      public Builder setVolumeMl(float value) {
        bitField0_ |= 0x00000004;
        volumeMl_ = value;
        onChanged();
        return this;
      }
      public Builder clearVolumeMl() {
        bitField0_ = (bitField0_ & ~0x00000004);
        volumeMl_ = 0F;
        onChanged();
        return this;
      }
      
      // optional string username = 4;
      private Object username_ = "";
      public boolean hasUsername() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getUsername() {
        Object ref = username_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          username_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUsername(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        username_ = value;
        onChanged();
        return this;
      }
      public Builder clearUsername() {
        bitField0_ = (bitField0_ & ~0x00000008);
        username_ = getDefaultInstance().getUsername();
        onChanged();
        return this;
      }
      void setUsername(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        username_ = value;
        onChanged();
      }
      
      // optional uint32 seconds_ago = 5 [default = 0];
      private int secondsAgo_ ;
      public boolean hasSecondsAgo() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public int getSecondsAgo() {
        return secondsAgo_;
      }
      public Builder setSecondsAgo(int value) {
        bitField0_ |= 0x00000010;
        secondsAgo_ = value;
        onChanged();
        return this;
      }
      public Builder clearSecondsAgo() {
        bitField0_ = (bitField0_ & ~0x00000010);
        secondsAgo_ = 0;
        onChanged();
        return this;
      }
      
      // optional string record_date = 6;
      private Object recordDate_ = "";
      public boolean hasRecordDate() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public String getRecordDate() {
        Object ref = recordDate_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          recordDate_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setRecordDate(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        recordDate_ = value;
        onChanged();
        return this;
      }
      public Builder clearRecordDate() {
        bitField0_ = (bitField0_ & ~0x00000020);
        recordDate_ = getDefaultInstance().getRecordDate();
        onChanged();
        return this;
      }
      void setRecordDate(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000020;
        recordDate_ = value;
        onChanged();
      }
      
      // optional uint32 duration_seconds = 7;
      private int durationSeconds_ ;
      public boolean hasDurationSeconds() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public int getDurationSeconds() {
        return durationSeconds_;
      }
      public Builder setDurationSeconds(int value) {
        bitField0_ |= 0x00000040;
        durationSeconds_ = value;
        onChanged();
        return this;
      }
      public Builder clearDurationSeconds() {
        bitField0_ = (bitField0_ & ~0x00000040);
        durationSeconds_ = 0;
        onChanged();
        return this;
      }
      
      // optional string auth_token = 8;
      private Object authToken_ = "";
      public boolean hasAuthToken() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public String getAuthToken() {
        Object ref = authToken_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          authToken_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setAuthToken(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        authToken_ = value;
        onChanged();
        return this;
      }
      public Builder clearAuthToken() {
        bitField0_ = (bitField0_ & ~0x00000080);
        authToken_ = getDefaultInstance().getAuthToken();
        onChanged();
        return this;
      }
      void setAuthToken(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000080;
        authToken_ = value;
        onChanged();
      }
      
      // optional bool spilled = 9;
      private boolean spilled_ ;
      public boolean hasSpilled() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      public boolean getSpilled() {
        return spilled_;
      }
      public Builder setSpilled(boolean value) {
        bitField0_ |= 0x00000100;
        spilled_ = value;
        onChanged();
        return this;
      }
      public Builder clearSpilled() {
        bitField0_ = (bitField0_ & ~0x00000100);
        spilled_ = false;
        onChanged();
        return this;
      }
      
      // optional string shout = 10;
      private Object shout_ = "";
      public boolean hasShout() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      public String getShout() {
        Object ref = shout_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          shout_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setShout(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        shout_ = value;
        onChanged();
        return this;
      }
      public Builder clearShout() {
        bitField0_ = (bitField0_ & ~0x00000200);
        shout_ = getDefaultInstance().getShout();
        onChanged();
        return this;
      }
      void setShout(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000200;
        shout_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:RecordDrinkRequest)
    }
    
    static {
      defaultInstance = new RecordDrinkRequest(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:RecordDrinkRequest)
  }
  
  public interface RecordTemperatureRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string sensor_name = 1;
    boolean hasSensorName();
    String getSensorName();
    
    // required float temp_c = 2;
    boolean hasTempC();
    float getTempC();
    
    // optional string record_date = 3;
    boolean hasRecordDate();
    String getRecordDate();
  }
  public static final class RecordTemperatureRequest extends
      com.google.protobuf.GeneratedMessage
      implements RecordTemperatureRequestOrBuilder {
    // Use RecordTemperatureRequest.newBuilder() to construct.
    private RecordTemperatureRequest(Builder builder) {
      super(builder);
    }
    private RecordTemperatureRequest(boolean noInit) {}
    
    private static final RecordTemperatureRequest defaultInstance;
    public static RecordTemperatureRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public RecordTemperatureRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.kegbot.proto.Api.internal_static_RecordTemperatureRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.kegbot.proto.Api.internal_static_RecordTemperatureRequest_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string sensor_name = 1;
    public static final int SENSOR_NAME_FIELD_NUMBER = 1;
    private Object sensorName_;
    public boolean hasSensorName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getSensorName() {
      Object ref = sensorName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          sensorName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getSensorNameBytes() {
      Object ref = sensorName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        sensorName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required float temp_c = 2;
    public static final int TEMP_C_FIELD_NUMBER = 2;
    private float tempC_;
    public boolean hasTempC() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public float getTempC() {
      return tempC_;
    }
    
    // optional string record_date = 3;
    public static final int RECORD_DATE_FIELD_NUMBER = 3;
    private Object recordDate_;
    public boolean hasRecordDate() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getRecordDate() {
      Object ref = recordDate_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          recordDate_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getRecordDateBytes() {
      Object ref = recordDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        recordDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      sensorName_ = "";
      tempC_ = 0F;
      recordDate_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasSensorName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTempC()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getSensorNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFloat(2, tempC_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getRecordDateBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getSensorNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, tempC_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getRecordDateBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    @java.lang.Override
    protected Object writeReplace() throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.kegbot.proto.Api.RecordTemperatureRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.kegbot.proto.Api.RecordTemperatureRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.kegbot.proto.Api.RecordTemperatureRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.kegbot.proto.Api.RecordTemperatureRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.kegbot.proto.Api.RecordTemperatureRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.kegbot.proto.Api.RecordTemperatureRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.kegbot.proto.Api.RecordTemperatureRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.kegbot.proto.Api.RecordTemperatureRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.kegbot.proto.Api.RecordTemperatureRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.kegbot.proto.Api.RecordTemperatureRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.kegbot.proto.Api.RecordTemperatureRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.kegbot.proto.Api.RecordTemperatureRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.kegbot.proto.Api.internal_static_RecordTemperatureRequest_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.kegbot.proto.Api.internal_static_RecordTemperatureRequest_fieldAccessorTable;
      }
      
      // Construct using org.kegbot.proto.Api.RecordTemperatureRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        sensorName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        tempC_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000002);
        recordDate_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.kegbot.proto.Api.RecordTemperatureRequest.getDescriptor();
      }
      
      public org.kegbot.proto.Api.RecordTemperatureRequest getDefaultInstanceForType() {
        return org.kegbot.proto.Api.RecordTemperatureRequest.getDefaultInstance();
      }
      
      public org.kegbot.proto.Api.RecordTemperatureRequest build() {
        org.kegbot.proto.Api.RecordTemperatureRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.kegbot.proto.Api.RecordTemperatureRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.kegbot.proto.Api.RecordTemperatureRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.kegbot.proto.Api.RecordTemperatureRequest buildPartial() {
        org.kegbot.proto.Api.RecordTemperatureRequest result = new org.kegbot.proto.Api.RecordTemperatureRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sensorName_ = sensorName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.tempC_ = tempC_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.recordDate_ = recordDate_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.kegbot.proto.Api.RecordTemperatureRequest) {
          return mergeFrom((org.kegbot.proto.Api.RecordTemperatureRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.kegbot.proto.Api.RecordTemperatureRequest other) {
        if (other == org.kegbot.proto.Api.RecordTemperatureRequest.getDefaultInstance()) return this;
        if (other.hasSensorName()) {
          setSensorName(other.getSensorName());
        }
        if (other.hasTempC()) {
          setTempC(other.getTempC());
        }
        if (other.hasRecordDate()) {
          setRecordDate(other.getRecordDate());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasSensorName()) {
          
          return false;
        }
        if (!hasTempC()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              sensorName_ = input.readBytes();
              break;
            }
            case 21: {
              bitField0_ |= 0x00000002;
              tempC_ = input.readFloat();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              recordDate_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string sensor_name = 1;
      private Object sensorName_ = "";
      public boolean hasSensorName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getSensorName() {
        Object ref = sensorName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          sensorName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setSensorName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        sensorName_ = value;
        onChanged();
        return this;
      }
      public Builder clearSensorName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sensorName_ = getDefaultInstance().getSensorName();
        onChanged();
        return this;
      }
      void setSensorName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        sensorName_ = value;
        onChanged();
      }
      
      // required float temp_c = 2;
      private float tempC_ ;
      public boolean hasTempC() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public float getTempC() {
        return tempC_;
      }
      public Builder setTempC(float value) {
        bitField0_ |= 0x00000002;
        tempC_ = value;
        onChanged();
        return this;
      }
      public Builder clearTempC() {
        bitField0_ = (bitField0_ & ~0x00000002);
        tempC_ = 0F;
        onChanged();
        return this;
      }
      
      // optional string record_date = 3;
      private Object recordDate_ = "";
      public boolean hasRecordDate() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getRecordDate() {
        Object ref = recordDate_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          recordDate_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setRecordDate(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        recordDate_ = value;
        onChanged();
        return this;
      }
      public Builder clearRecordDate() {
        bitField0_ = (bitField0_ & ~0x00000004);
        recordDate_ = getDefaultInstance().getRecordDate();
        onChanged();
        return this;
      }
      void setRecordDate(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        recordDate_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:RecordTemperatureRequest)
    }
    
    static {
      defaultInstance = new RecordTemperatureRequest(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:RecordTemperatureRequest)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Meta_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Meta_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_UserRegistrationRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_UserRegistrationRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_RecordDrinkRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RecordDrinkRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_RecordTemperatureRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RecordTemperatureRequest_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tapi.proto\032\014models.proto\"1\n\004Meta\022\r\n\005tot" +
      "al\030\001 \001(\r\022\r\n\005limit\030\002 \001(\r\022\013\n\003pos\030\003 \001(\r\"r\n\027" +
      "UserRegistrationRequest\022\020\n\010username\030\001 \002(" +
      "\t\022\r\n\005email\030\002 \002(\t\022\020\n\010password\030\003 \001(\t\022\016\n\006ge" +
      "nder\030\004 \001(\t\022\024\n\014twitter_name\030\005 \001(\t\"\325\001\n\022Rec" +
      "ordDrinkRequest\022\020\n\010tap_name\030\001 \001(\t\022\r\n\005tic" +
      "ks\030\002 \002(\r\022\021\n\tvolume_ml\030\003 \001(\002\022\020\n\010username\030" +
      "\004 \001(\t\022\026\n\013seconds_ago\030\005 \001(\r:\0010\022\023\n\013record_" +
      "date\030\006 \001(\t\022\030\n\020duration_seconds\030\007 \001(\r\022\022\n\n" +
      "auth_token\030\010 \001(\t\022\017\n\007spilled\030\t \001(\010\022\r\n\005sho",
      "ut\030\n \001(\t\"T\n\030RecordTemperatureRequest\022\023\n\013" +
      "sensor_name\030\001 \002(\t\022\016\n\006temp_c\030\002 \002(\002\022\023\n\013rec" +
      "ord_date\030\003 \001(\tB\022\n\020org.kegbot.proto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Meta_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Meta_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Meta_descriptor,
              new java.lang.String[] { "Total", "Limit", "Pos", },
              org.kegbot.proto.Api.Meta.class,
              org.kegbot.proto.Api.Meta.Builder.class);
          internal_static_UserRegistrationRequest_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_UserRegistrationRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_UserRegistrationRequest_descriptor,
              new java.lang.String[] { "Username", "Email", "Password", "Gender", "TwitterName", },
              org.kegbot.proto.Api.UserRegistrationRequest.class,
              org.kegbot.proto.Api.UserRegistrationRequest.Builder.class);
          internal_static_RecordDrinkRequest_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_RecordDrinkRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_RecordDrinkRequest_descriptor,
              new java.lang.String[] { "TapName", "Ticks", "VolumeMl", "Username", "SecondsAgo", "RecordDate", "DurationSeconds", "AuthToken", "Spilled", "Shout", },
              org.kegbot.proto.Api.RecordDrinkRequest.class,
              org.kegbot.proto.Api.RecordDrinkRequest.Builder.class);
          internal_static_RecordTemperatureRequest_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_RecordTemperatureRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_RecordTemperatureRequest_descriptor,
              new java.lang.String[] { "SensorName", "TempC", "RecordDate", },
              org.kegbot.proto.Api.RecordTemperatureRequest.class,
              org.kegbot.proto.Api.RecordTemperatureRequest.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.kegbot.proto.Models.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
