// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: internal.proto

package org.kegbot.proto;

public final class Internal {
  private Internal() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PendingPourOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .RecordDrinkRequest drink_request = 1;
    boolean hasDrinkRequest();
    org.kegbot.proto.Api.RecordDrinkRequest getDrinkRequest();
    org.kegbot.proto.Api.RecordDrinkRequestOrBuilder getDrinkRequestOrBuilder();
    
    // repeated string images = 2;
    java.util.List<String> getImagesList();
    int getImagesCount();
    String getImages(int index);
  }
  public static final class PendingPour extends
      com.google.protobuf.GeneratedMessage
      implements PendingPourOrBuilder {
    // Use PendingPour.newBuilder() to construct.
    private PendingPour(Builder builder) {
      super(builder);
    }
    private PendingPour(boolean noInit) {}
    
    private static final PendingPour defaultInstance;
    public static PendingPour getDefaultInstance() {
      return defaultInstance;
    }
    
    public PendingPour getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.kegbot.proto.Internal.internal_static_PendingPour_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.kegbot.proto.Internal.internal_static_PendingPour_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required .RecordDrinkRequest drink_request = 1;
    public static final int DRINK_REQUEST_FIELD_NUMBER = 1;
    private org.kegbot.proto.Api.RecordDrinkRequest drinkRequest_;
    public boolean hasDrinkRequest() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public org.kegbot.proto.Api.RecordDrinkRequest getDrinkRequest() {
      return drinkRequest_;
    }
    public org.kegbot.proto.Api.RecordDrinkRequestOrBuilder getDrinkRequestOrBuilder() {
      return drinkRequest_;
    }
    
    // repeated string images = 2;
    public static final int IMAGES_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList images_;
    public java.util.List<String>
        getImagesList() {
      return images_;
    }
    public int getImagesCount() {
      return images_.size();
    }
    public String getImages(int index) {
      return images_.get(index);
    }
    
    private void initFields() {
      drinkRequest_ = org.kegbot.proto.Api.RecordDrinkRequest.getDefaultInstance();
      images_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasDrinkRequest()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getDrinkRequest().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, drinkRequest_);
      }
      for (int i = 0; i < images_.size(); i++) {
        output.writeBytes(2, images_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, drinkRequest_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < images_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(images_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getImagesList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    @java.lang.Override
    protected Object writeReplace() throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.kegbot.proto.Internal.PendingPour parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.kegbot.proto.Internal.PendingPour parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.kegbot.proto.Internal.PendingPour parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.kegbot.proto.Internal.PendingPour parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.kegbot.proto.Internal.PendingPour parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.kegbot.proto.Internal.PendingPour parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.kegbot.proto.Internal.PendingPour parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.kegbot.proto.Internal.PendingPour parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.kegbot.proto.Internal.PendingPour parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.kegbot.proto.Internal.PendingPour parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.kegbot.proto.Internal.PendingPour prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.kegbot.proto.Internal.PendingPourOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.kegbot.proto.Internal.internal_static_PendingPour_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.kegbot.proto.Internal.internal_static_PendingPour_fieldAccessorTable;
      }
      
      // Construct using org.kegbot.proto.Internal.PendingPour.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getDrinkRequestFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (drinkRequestBuilder_ == null) {
          drinkRequest_ = org.kegbot.proto.Api.RecordDrinkRequest.getDefaultInstance();
        } else {
          drinkRequestBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        images_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.kegbot.proto.Internal.PendingPour.getDescriptor();
      }
      
      public org.kegbot.proto.Internal.PendingPour getDefaultInstanceForType() {
        return org.kegbot.proto.Internal.PendingPour.getDefaultInstance();
      }
      
      public org.kegbot.proto.Internal.PendingPour build() {
        org.kegbot.proto.Internal.PendingPour result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.kegbot.proto.Internal.PendingPour buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.kegbot.proto.Internal.PendingPour result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.kegbot.proto.Internal.PendingPour buildPartial() {
        org.kegbot.proto.Internal.PendingPour result = new org.kegbot.proto.Internal.PendingPour(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (drinkRequestBuilder_ == null) {
          result.drinkRequest_ = drinkRequest_;
        } else {
          result.drinkRequest_ = drinkRequestBuilder_.build();
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          images_ = new com.google.protobuf.UnmodifiableLazyStringList(
              images_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.images_ = images_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.kegbot.proto.Internal.PendingPour) {
          return mergeFrom((org.kegbot.proto.Internal.PendingPour)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.kegbot.proto.Internal.PendingPour other) {
        if (other == org.kegbot.proto.Internal.PendingPour.getDefaultInstance()) return this;
        if (other.hasDrinkRequest()) {
          mergeDrinkRequest(other.getDrinkRequest());
        }
        if (!other.images_.isEmpty()) {
          if (images_.isEmpty()) {
            images_ = other.images_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureImagesIsMutable();
            images_.addAll(other.images_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasDrinkRequest()) {
          
          return false;
        }
        if (!getDrinkRequest().isInitialized()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              org.kegbot.proto.Api.RecordDrinkRequest.Builder subBuilder = org.kegbot.proto.Api.RecordDrinkRequest.newBuilder();
              if (hasDrinkRequest()) {
                subBuilder.mergeFrom(getDrinkRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setDrinkRequest(subBuilder.buildPartial());
              break;
            }
            case 18: {
              ensureImagesIsMutable();
              images_.add(input.readBytes());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .RecordDrinkRequest drink_request = 1;
      private org.kegbot.proto.Api.RecordDrinkRequest drinkRequest_ = org.kegbot.proto.Api.RecordDrinkRequest.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.kegbot.proto.Api.RecordDrinkRequest, org.kegbot.proto.Api.RecordDrinkRequest.Builder, org.kegbot.proto.Api.RecordDrinkRequestOrBuilder> drinkRequestBuilder_;
      public boolean hasDrinkRequest() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public org.kegbot.proto.Api.RecordDrinkRequest getDrinkRequest() {
        if (drinkRequestBuilder_ == null) {
          return drinkRequest_;
        } else {
          return drinkRequestBuilder_.getMessage();
        }
      }
      public Builder setDrinkRequest(org.kegbot.proto.Api.RecordDrinkRequest value) {
        if (drinkRequestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          drinkRequest_ = value;
          onChanged();
        } else {
          drinkRequestBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder setDrinkRequest(
          org.kegbot.proto.Api.RecordDrinkRequest.Builder builderForValue) {
        if (drinkRequestBuilder_ == null) {
          drinkRequest_ = builderForValue.build();
          onChanged();
        } else {
          drinkRequestBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder mergeDrinkRequest(org.kegbot.proto.Api.RecordDrinkRequest value) {
        if (drinkRequestBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              drinkRequest_ != org.kegbot.proto.Api.RecordDrinkRequest.getDefaultInstance()) {
            drinkRequest_ =
              org.kegbot.proto.Api.RecordDrinkRequest.newBuilder(drinkRequest_).mergeFrom(value).buildPartial();
          } else {
            drinkRequest_ = value;
          }
          onChanged();
        } else {
          drinkRequestBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder clearDrinkRequest() {
        if (drinkRequestBuilder_ == null) {
          drinkRequest_ = org.kegbot.proto.Api.RecordDrinkRequest.getDefaultInstance();
          onChanged();
        } else {
          drinkRequestBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      public org.kegbot.proto.Api.RecordDrinkRequest.Builder getDrinkRequestBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getDrinkRequestFieldBuilder().getBuilder();
      }
      public org.kegbot.proto.Api.RecordDrinkRequestOrBuilder getDrinkRequestOrBuilder() {
        if (drinkRequestBuilder_ != null) {
          return drinkRequestBuilder_.getMessageOrBuilder();
        } else {
          return drinkRequest_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          org.kegbot.proto.Api.RecordDrinkRequest, org.kegbot.proto.Api.RecordDrinkRequest.Builder, org.kegbot.proto.Api.RecordDrinkRequestOrBuilder> 
          getDrinkRequestFieldBuilder() {
        if (drinkRequestBuilder_ == null) {
          drinkRequestBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.kegbot.proto.Api.RecordDrinkRequest, org.kegbot.proto.Api.RecordDrinkRequest.Builder, org.kegbot.proto.Api.RecordDrinkRequestOrBuilder>(
                  drinkRequest_,
                  getParentForChildren(),
                  isClean());
          drinkRequest_ = null;
        }
        return drinkRequestBuilder_;
      }
      
      // repeated string images = 2;
      private com.google.protobuf.LazyStringList images_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureImagesIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          images_ = new com.google.protobuf.LazyStringArrayList(images_);
          bitField0_ |= 0x00000002;
         }
      }
      public java.util.List<String>
          getImagesList() {
        return java.util.Collections.unmodifiableList(images_);
      }
      public int getImagesCount() {
        return images_.size();
      }
      public String getImages(int index) {
        return images_.get(index);
      }
      public Builder setImages(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureImagesIsMutable();
        images_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addImages(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureImagesIsMutable();
        images_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllImages(
          java.lang.Iterable<String> values) {
        ensureImagesIsMutable();
        super.addAll(values, images_);
        onChanged();
        return this;
      }
      public Builder clearImages() {
        images_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      void addImages(com.google.protobuf.ByteString value) {
        ensureImagesIsMutable();
        images_.add(value);
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:PendingPour)
    }
    
    static {
      defaultInstance = new PendingPour(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:PendingPour)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_PendingPour_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PendingPour_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016internal.proto\032\tapi.proto\032\014models.prot" +
      "o\"I\n\013PendingPour\022*\n\rdrink_request\030\001 \002(\0132" +
      "\023.RecordDrinkRequest\022\016\n\006images\030\002 \003(\tB\022\n\020" +
      "org.kegbot.proto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_PendingPour_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_PendingPour_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_PendingPour_descriptor,
              new java.lang.String[] { "DrinkRequest", "Images", },
              org.kegbot.proto.Internal.PendingPour.class,
              org.kegbot.proto.Internal.PendingPour.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.kegbot.proto.Api.getDescriptor(),
          org.kegbot.proto.Models.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
