name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Build the app
        run: ./gradlew build

      - name: Archive debug APK
        uses: actions/upload-artifact@v3
        with:
          name: kegtab-debug
          path: kegtab/build/outputs/apk/debug/kegtab-debug.apk

      - name: Archive release APK
        uses: actions/upload-artifact@v3
        with:
          name: kegtab-release-unsigned
          path: kegtab/build/outputs/apk/release/kegtab-release-unsigned.apk
